[package]
name = "solana-program-rosetta-helloworld"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2"

[dev-dependencies]
solana-program-test = "2"
solana-sdk = "2"

[lib]
crate-type = ["cdylib", "lib"]
